// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA9U6jW4dEeno1BTE79zoZTSbnrvsMGNM',
    appId: '1:697109261807:web:38a6326b6b4fdb9ba41a1a',
    messagingSenderId: '697109261807',
    projectId: 'task1-4f117',
    authDomain: 'task1-4f117.firebaseapp.com',
    storageBucket: 'task1-4f117.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsF_mZy2fBblWDlI5SSbR2B-BN1WF8E1E',
    appId: '1:697109261807:android:46c06797fcac54aca41a1a',
    messagingSenderId: '697109261807',
    projectId: 'task1-4f117',
    storageBucket: 'task1-4f117.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc8EtfB5c6yj-IXJ-EQYJSDTSoSExJ3b4',
    appId: '1:697109261807:ios:6b5245dc5e99e4a6a41a1a',
    messagingSenderId: '697109261807',
    projectId: 'task1-4f117',
    storageBucket: 'task1-4f117.firebasestorage.app',
    iosClientId: '697109261807-0f19o2pq1gqc7i8cup4fgtqio6tl297j.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniWhatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc8EtfB5c6yj-IXJ-EQYJSDTSoSExJ3b4',
    appId: '1:697109261807:ios:6b5245dc5e99e4a6a41a1a',
    messagingSenderId: '697109261807',
    projectId: 'task1-4f117',
    storageBucket: 'task1-4f117.firebasestorage.app',
    iosClientId: '697109261807-0f19o2pq1gqc7i8cup4fgtqio6tl297j.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniWhatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA9U6jW4dEeno1BTE79zoZTSbnrvsMGNM',
    appId: '1:697109261807:web:f3903645ec2b06e4a41a1a',
    messagingSenderId: '697109261807',
    projectId: 'task1-4f117',
    authDomain: 'task1-4f117.firebaseapp.com',
    storageBucket: 'task1-4f117.firebasestorage.app',
  );
}
